### ISSUE TITLE
SFTP with private rsa key

### ISSUE THREAD

**Issue by santafirst** [i22-digitalagentur/sftp_client#11]
HI,
I'm trying to make a SFTP connection with private rsa key. 
The service works and i can reach it with CLI and filezilla.

I tried a lot of config combination. The key is a classic `id_rsa`.  the keys are generated with `ssh-keygen` command on cli.
I tried with something like `[host: 'sftp', user: 'user', user_dir: 'keys', private_key_path: 'keys/id_rsa']` and also implementing manually a `key_cb` but i receive the same error everytime.
The error i get is this one:
```
10:16:06.539 [info]  Erlang SSH :client 4.9 (OpenSSL 1.1.1d  10 Sep 2019).
Server: 'SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u4'
Disconnects with code = 14 [RFC4253 11.1]: Unable to connect using the available authentication methods
State = {userauth,client}
Module = ssh_connection_handler, Line = 931.
Details:
  User auth failed for: "user"


{:error,
 %SFTPClient.ConnError{
   message: "Unable to connect using the available authentication methods"
 }}
```

Looking at the `State` in the error, it seems that is missing the public/private key authentication method, but i can't find a solution.

Do you have some ideas why this doesn't work? What am I doing wrong?

Thanks

**Comment by tlux** [comment]
Thank you very much for your bug report!

I'm taking a look into it as soon as I can. May take some days though 🙂

**Comment by tlux** [comment]
As it turned out, this issue comes due to lacking support for OpenSSH private keys in OTP

A discussion about the topic and a possible workaround can be found in the SSHEx repo:
https://github.com/rubencaro/sshex/issues/22

The easiest workaround is probably to convert your OpenSSH key to PKCS8 using the `ssh-keygen` tool - if this is an option for you.

Nevertheless, it would be desirable to support OpenSSH keys directly in SFTPClient. Thus, I'm leaving this issue open.

**Comment by santafirst** [comment]
@tlux thanks a lot! yes, after some tries it worked with a normal RSA key. Thanks for the answer and hoping that next OTP will support also OpenSSH keys!

**Comment by Efesto** [comment]
I've created a PR for addressing this issue by using a different decoding method: https://github.com/tlux/sftp_client/pull/28
