### ISSUE TITLE
Protocol Collectable not implemented for %SFTPClient.Stream

### ISSUE THREAD

**Issue by crsmillan** [i22-digitalagentur/sftp_client#12]
Hi i'm trying to upload a file using `SFTPClient.upload_file!(conn, local_path, remote_path)`.

but i'm getting 

`(Protocol.UndefinedError) protocol Collectable not implemented for %SFTPClient.Stream{chunk_size: 32768, conn: %SFTPClient.Conn{channel_pid: #PID<0.661.0>, config: %SFTPClient.Config{connect_timeout: 5000, dsa_pass_phrase: nil, ecdsa_pass_phrase: nil, host: "host_ip", inet: :inet, key_cb: {SFTPClient.KeyProvider, [private_key_path: nil, private_key_pass_phrase: nil]}, operation_timeout: :infinity, password: nil, port: port, private_key_pass_phrase: nil, private_key_path: nil, rsa_pass_phrase: 'secret, sftp_vsn: nil, system_dir: nil, user: 'user', user_dir: 'keys_dir'}, conn_ref: #PID<0.659.0>}, path: "remote_path"} of type SFTPClient.Stream (a struct). This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, IO.Stream, HashDict, File.Stream, Map, MapSet, HashSet, BitString, List
    (elixir 1.10.2) lib/collectable.ex:1: Collectable.impl_for!/1
    (elixir 1.10.2) lib/collectable.ex:77: Collectable.into/1
    (elixir 1.10.2) lib/stream.ex:531: Stream.do_into/5
    (elixir 1.10.2) lib/stream.ex:649: Stream.run/1
    (sftp_client 1.4.0) lib/sftp_client/operations/upload_file.ex:37: SFTPClient.Operations.UploadFile.upload_file!/3`

what do i am doing wrong?

**Comment by tlux** [comment]
Hello, thank you for your bug report!

Which version of Elixir and OTP are you using?
Are you using any frameworks - such as Phoenix?

**Comment by crsmillan** [comment]
Hello @tlux , i hope you're well.

I'm using Elixir 1.10.2 and Erlang/OTP 22, 
and i'm not using Phoenix, but i use https://github.com/CrowdHailer/Ace as a web server

**Comment by tlux** [comment]
I'm kind of lost at the moment because there are a couple of green tests for this particular function that involve the protocol implementation. 
I will probably have to reconstruct your project setup.
One more question: Did you play around with the `:consolidate_protocols` option in your Mix project?

**Comment by faigyLang** [comment]
I am getting the same error, 
using Elixir 1.9.4 and Erlang/OTP 22
I have an umbrella app, and it actually only happens when i run the app from the base directory of the umbrella - which uses phoenix.    
 when I only run this specific app (which does not use phoenix) it works just fine.   
Does it really have to do with using phoenix? And is there a way to solve it?
oh, and i did not change the `: consolidate_protocols` option

**Comment by tlux** [comment]
Hello @faigyLang,

thank you for your message. 

After some digging, I found an (older) issue in the official Elixir issue board (https://github.com/elixir-lang/elixir/issues/5987). It seems that umbrella apps need some "special care" - most notably running `mix compile.protocols --force`. Maybe you try some of the described workarounds and then report back here!

**Comment by faigyLang** [comment]
Thanks @tlux !    
running `mix compile.protocols --force` did solve the problem.    
i will check it in to get a better understanding of the issue.

**Comment by tlux** [comment]
Great, you're welcome! I'm closing this issue for now.

**Comment by crsmillan** [comment]
Amazing guys 🎊
