### ISSUE TITLE
(FunctionClauseError) no function clause matching in :ssh.connect/4 

### ISSUE THREAD

**Issue by nmenag** [i22-digitalagentur/sftp_client#21]
Error to connect to SFTP
```elixir
The following arguments were given to :ssh.connect/4:
    
        # 1
        'host'
    
        # 2
        "9003"
    
        # 3
        [
          user_interaction: false,
          user: 'admin',
          silently_accept_hosts: true,
          quiet_mode: true,
          password: 'admin!',
          key_cb: {SFTPClient.KeyProvider,
           [private_key_path: nil, private_key_pass_phrase: nil]},
          inet: :inet,
          connect_timeout: 5000
        ]
  
        # 4
        5000

```

call:

`{:ok, conn} = SFTPClient.connect(host: "host", user: "admin", password: "admin", port: "9003")`

**Comment by wkirschbaum** [comment]
@nmenag port must be a number between 0..65535, not a string. http://erlang.org/doc/man/inet.html#type-port_number

**Comment by nmenag** [comment]
@wkirschbaum yes I tried that, but now it's returning this error: 

```
Erlang SSH :client 4.10.2 (OpenSSL 1.1.1f  31 Mar 2020).
Server: 'SSH-2.0-WeOnlyDo-wodFTPD 3.3.0.424'
Disconnects with code = 3 [RFC4253 11.1]: Key exchange failed
State = {kexinit,client,init}
Module = ssh_transport, Line = 380.
Details:
  Kexinit failed in client: error:{badmatch,{false,"kex"}}


** (MatchError) no match of right hand side value: {:error, %SFTPClient.ConnError{message: "Key exchange failed"}}
```
it is not working ok on Linux. I have no idea what configurations I need for works well on Linux.  in Mac works.

**Comment by tlux** [comment]
Hello! Thank you for reporting this issue. 

Which Erlang/OTP version are you using on your Linux system? Probably OTP 23?

I think it might be an issue due to a change in Erlang's ssh module in the recent OTP (23) version. 

However, there is [an open issue](https://github.com/bitcrowd/sshkit.ex/issues/156#issuecomment-629968922) in the SSHKit library which seems to be very similar. It points out that there have been a couple changes in OTP 23 - some key exchange algorithms in OTP 23 have been deprecated, for instance. There are also some hints on how to deal with the issue. 

If this still does not help, you probably want to downgrade to OTP 22 until a proper fix is implemented.
